[versions]
agp = "8.7.3"
barcodeScanning = "17.3.0"
zxing = "3.4.1"
kotlin = "2.1.0"
coreKtx = "1.15.0"
appcompat = "1.7.0"
activity = "1.9.3"
material = "1.12.0"
glance = "1.1.1"
zxingAndroidEmbedded = "4.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
zxing = { module = "com.google.zxing:core", version.ref = "zxing" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

