[versions]
buildTools = "35.0.0"
android-compileSdk = "35"
android-minSdk = "31"
android-targetSdk = "35"

agp = "8.8.0"
kotlin = "2.1.0"
core = "1.15.0"
appcompat = "1.7.0"
activity = "1.9.3"
material = "1.3.1"
glance = "1.1.1"

barcode = "17.3.0"

zxing = "3.4.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }

material-compose = { group = "androidx.compose.material3", name = "material3", version.ref = "material" }

glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }

barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcode" }

zxing = { module = "com.google.zxing:core", version.ref = "zxing" }

[plugins]
android-gradle = { id = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradle = { id = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

android-application = { id = "com.android.application" }
android-library = { id = "com.android.library" }
kotlin-android = { id = "org.jetbrains.kotlin.android" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm" }
javaLibrary = { id = "java-library" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose" }

